name: First CI Workflow

on:
  push:
    branches:
      - main

jobs:
  git-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run shell script
        run: bash hello.sh

      - name: Run shell script
        run: bash test.sh

      - name: Success message
        if: success()
        run: echo "All test passed successfully!"

      - name: Failure messages
        if: failure()
        run: echo "Something went wrong!"

      - name: Final message
        if: always()
        run: echo "Workflow execution completed"

      - name: List repository files
        run: ls

      - name: Git message
        run: echo "I am learning Git."

  github-job:
    needs: git-job
    runs-on: ubuntu-latest
    steps:
      - name: GitHub message
        run: echo "I am learning GitHub Actions."
