name: First CI Workflow

on:
  push:
    branches:
      - main

jobs:
  git-job:
    runs-on: ubuntu-latest
    steps:
      - name: Git message
        run: echo "I am learning Git."

  github-job:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub message
        run: echo "I am learning GitHub Actions."
        
  github-jobss:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub message
        run: echo " GitHub Actions."
